name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          run: |
            npm ci
            npm run build:win --if-present

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/**'
          body: 'Release ${{ github.ref }}'
          generateReleaseNotes: 'true'
